name: Assemble Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate short SHA
        id: set-short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Download and Setup the Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Install CMake in the Android SDK
        # This is the same version of cmake that is found in build.gradle. This
        # will be used to build libavif and the JNI bindings.
        run: sdkmanager "cmake;3.22.1"

      - name: Download and Setup the Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          # r25c is the same as 25.2.9519653.
          ndk-version: r25c
          add-to-path: false

      - name: Grant Execute Permission
        run: chmod +x ./gradlew

      - name: Build a debug APK
        run: ./gradlew assembleDebug

      - name: Upload app-arm64-v8a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-arm64-v8a-debug-unsigned.apk
      
      - name: Upload app-armeabi-v7a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-armeabi-v7a-debug-unsigned.apk
      
      - name: Upload app-universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-universal-release-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-universal-debug-unsigned.apk
      
      - name: Upload app-x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-x86-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-x86-debug-unsigned.apk
      
      - name: Upload app-x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-x86_64-debug-unsigned.apk
      
      - name: Upload app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-debug-unsigned.apk
