name: Assemble Debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate short SHA
        id: set-short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Grant Execute Permission
        run: chmod +x ./gradlew

      - name: Build a debug APK
        run: ./gradlew assembleDebug

      - name: Upload app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-unsigned-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-debug-unsigned.apk
