name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
  
jobs:
  sync:

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          #token: ${{ github.token }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: Android-Media-Converter
          owner: scto
          base: master
          head: master
          merge_method:	merge
